//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           |/|
        ///          |/|
        ///          |/| /¯)
        ///          |/|/\/
        ///          |/|\/
        ///         (¯¯¯)
        ///         (¯¯¯)
        ///         (¯¯¯)
        ///         /¯¯/\
        ///        / ,^./\
        ///       / /   \/\
        ///      / /     \/\
        ///     ( (       )/)
        ///     | |       |/|
        ///     ( (       )/)
        ///      \ \     / /
        ///       \ `---&apos; /
        ///        `-----&apos;    .
        /// </summary>
        internal static string lose {
            get {
                return ResourceManager.GetString("lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            ▄ .▄ ▄▄▄·  ▐ ▄  ▄▄ • • ▌ ▄ ·.  ▄▄▄·  ▐ ▄ 
        ///          ██▪▐█▐█ ▀█ •█▌▐█▐█ ▀ ▪·██ ▐███▪▐█ ▀█ •█▌▐█
        ///          ██▀▐█▄█▀▀█ ▐█▐▐▌▄█ ▀█▄▐█ ▌▐▌▐█·▄█▀▀█ ▐█▐▐▌
        ///          ██▌▐▀▐█ ▪▐▌██▐█▌▐█▄▪▐███ ██▌▐█▌▐█ ▪▐▌██▐█▌
        ///          ▀▀▀ · ▀  ▀ ▀▀ █▪·▀▀▀▀ ▀▀  █▪▀▀▀ ▀  ▀ ▀▀ █▪.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///                  __    __)                 
        ///                 (, )  /  ,                 
        ///                    | /     _ _/_ _____     
        ///                    |/  _(_(__(__(_)/ (_(_/_
        ///                    |                  .-/  
        ///                                      (_/   .
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM
        ///CD
        ///TV
        ///aardvark
        ///abacus
        ///abbey
        ///abbreviation
        ///abdomen
        ///ability
        ///abnormality
        ///abolishment
        ///abortion
        ///abrogation
        ///absence
        ///abundance
        ///abuse
        ///academics
        ///academy
        ///accelerant
        ///accelerator
        ///accent
        ///acceptance
        ///access
        ///accessory
        ///accident
        ///accommodation
        ///accompanist
        ///accomplishment
        ///accord
        ///accordance
        ///accordion
        ///account
        ///accountability
        ///accountant
        ///accounting
        ///accuracy
        ///accusation
        ///acetate
        ///achievement
        ///achiever
        ///acid
        ///acknowledgment
        ///acorn
        ///acoustics
        ///acquaintance
        ///acquisition
        ///acre
        ///acrylic
        ///act
        ///action
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
